### ISSUE TITLE
IR Data Thinning v2

### ISSUE THREAD

**Issue by captainkirkby** [captainkirkby/Gears#37]
(Ported from #24)
New Plan: ([source](https://blog.compose.io/sizing-and-trimming-your-mongodb/))

Using Mongo's repair database functionality is the only way to reclaim already allocated space.  However, this comes with a major disadvantage of not being able to write to the database while repair is running.

Mongo (and mongoose) has a feature called TTL (time to live) that can expire a **whole document** and deallocate its space for use by a future document.  However, this requires the data we're expiring (the IR data) to be in its own Mongo collection (organization we had suggested earlier anyways)

Big things to change are:
* add a new schema for the raw data (rawDataSchema) and model (rawDataModel)
* add a TTL field in the rawDataSchema
* save raw data to new model (rawDataModel)
* update web request to get data from new model (rawDataModel)

However, the TTL field is on the schema, so its applied to **every** document in the collections.  And we want to keep two consecutive swings every n.  I have a workaround that allows us to only expire certain documents.  The schema below expires every document after 120 seconds.

```
var testSchema = mongoose.Schema({
	timestamp		: { type: Date, expires: 120 },
});
```

But by setting timestamp to null, mongo cannot index the date and the document never expires.

**Comment by dkirkby** [comment]
What's a "document" in this context and how does it relate to the model we use to write data?  Do we have to explicitly close the document before it can be expired, or worry about a document expiring while we are still writing to it?

**Comment by captainkirkby** [comment]
DBs (TickTock) contain >> Collections (dataPacketModel, rawDataModel) contain >> Documents ({timestamp:3/5/15@10:51pm, raw:[...]})

Each document gets written to the collection as it comes through the serial port.  The database connection remains open, and a builtin background process that runs about once a minute cleans up any documents that have expired.  Writing to the documents is fast enough that we don't have to worry about expiring something while its being written.  Plus the expiry time is 1 day

**Comment by captainkirkby** [comment]
From Guilherme Souza at the Mongoose Google Group

Begin quote:
Hello Dylan,

This is an intended behavior in MongoDB [1]:
"If the indexed field in a document is not a date or an array that holds a date value(s), the document will not expire. If a document does not contain the indexed field, the document will not expire"

If you want to set different expire times to each document, consider the example in the MongoDB doc [2]:
"db.log_events.createIndex( { "expireAt": 1 }, { expireAfterSeconds: 0 } )"

Just keep in mind that a TTL index does not come free of charge. MongoDB will run a thread in the background every minute to remove expired documents.
On top of that, expiring 98% of the docs is likely to result in a very fragmented data file. Maybe a compact [3] command once in a while could be useful.

Test your solution under your work load to see if this overhead is tolerable :)

[1] http://docs.mongodb.org/manual/core/index-ttl/#expiration-of-data
[2] http://docs.mongodb.org/manual/tutorial/expire-data/#expire-documents-at-a-specific-clock-time
[3] http://docs.mongodb.org/manual/reference/command/compact/
End quote
