### ISSUE TITLE
New Wider Fingers

### ISSUE THREAD

**Issue by captainkirkby** [captainkirkby/Gears#39]
Updating the software to use new hardware: wider fingers machined and sent to us by Martin.  The idea of these is more edges gives us more accuracy in timing and a notch in the middle gives us a pendulum height measurement as well.

Things we need to change (following data flow):

1. Install Wider Fingers. ✓
2. Increase length of MCU raw buffer to record entire swing (wider now). ✓
  * Increase max number of tries in ADC test. ✓
3. Modify Logger to accept new data size.
4. Modify Fit to process new data size and shape.
5. Modify Server to serve new data size (?).

![Wider Fingers](https://cloud.githubusercontent.com/assets/3489773/6811410/d09a038c-d224-11e4-85ee-bbc0b908d660.png)

**Comment by captainkirkby** [comment]
New Buffer Size calculation:

![size=2048](https://cloud.githubusercontent.com/assets/3489773/6813582/b223a7a0-d233-11e4-9525-c0302e4ba92a.png)

Gets half the waveform in 1300 samples, so new waveform should take up at least 2600 samples.

The new buffer size = 2600

**Comment by dkirkby** [comment]
Looks good!  The rising slope of the short finger is interesting. Does it
go in the opposite direction when the swing is in the opposite direction?

**Comment by captainkirkby** [comment]
I was looking at that, it does!

![screenshot](https://cloud.githubusercontent.com/assets/3489773/6813700/d5f73e8e-d234-11e4-9b5c-ffc475de3772.png)

**Comment by captainkirkby** [comment]
![Full Waveform](https://cloud.githubusercontent.com/assets/3489773/6813925/12e9d0a2-d237-11e4-927c-f4e94c6783c6.png)

**Comment by dkirkby** [comment]
Perhaps this means the fingers are not mounted exactly perpendicular to the
pendulum rod?

**Comment by captainkirkby** [comment]
I think if that were the case it would look sloped on all of the notches.

**Comment by captainkirkby** [comment]
Update: The slant was because of some play in the mounting.

3072 is not enough samples, so we have to increase to ~300 more?

**Comment by captainkirkby** [comment]
Looks like 3328 is too much!

Here is a distribution graph of the time of each major operation: (Recording, read BMP, read GPS, send via UART) with 3328 and 3072 samples.  Note that the recording section will expand as it waits for a rising edge.


Figure 1:
![mcu time distribution per major operation - 3328](https://cloud.githubusercontent.com/assets/3489773/6882522/cbeeab44-d544-11e4-8cfe-457c10ab88b6.jpg)

Figure 2:
![mcu time distribution per major operation - 3072](https://cloud.githubusercontent.com/assets/3489773/6882524/d5b69862-d544-11e4-9465-2a90b4f70025.jpg)

Scope Captures:
3328
![img_3280](https://cloud.githubusercontent.com/assets/3489773/6882531/ee6bb662-d544-11e4-8438-e00ab294ef1d.JPG)
3072
![img_3281](https://cloud.githubusercontent.com/assets/3489773/6882532/f1fd7cb6-d544-11e4-9f9a-9afe5010eef7.JPG)

**Comment by captainkirkby** [comment]
Templating works now, and it is generated, but its screwy.  New Issue!
