### ISSUE TITLE
Templating Issues

### ISSUE THREAD

**Issue by captainkirkby** [captainkirkby/Gears#41]
With the new wider buffer, the high and low and midpoint calculations are all off now.

This is what the template looks like:
![screenshot](https://cloud.githubusercontent.com/assets/3489773/6882613/a8619124-d548-11e4-924d-c396b6b510f3.png)

Zooming in shows the waveform is still there:
![screenshot](https://cloud.githubusercontent.com/assets/3489773/6882614/a9a2f5f0-d548-11e4-971b-4fe89d89f823.png)

IPython Notebook of lo-mid-hi detection:
http://nbviewer.ipython.org/gist/captainkirkby/97d0a8c5321d35af45a7

**Comment by captainkirkby** [comment]
The main issue is in the way the template is generated and then used in the minimized chi-squared function.

When the default --spline-pad value of 0.25 (or anything nonzero) is used, the template behaves badly at the ends because there used to be data there, but now there isn't.  (See issue #39)

At 0.05 the template starts to get messed up...
![screenshot](https://cloud.githubusercontent.com/assets/3489773/6955282/1c0c4d22-d890-11e4-9060-e5cf085412e7.png)

...and at 0.25 the template is completely hidden by big downswings.
![screenshot](https://cloud.githubusercontent.com/assets/3489773/6955284/1ee376f6-d890-11e4-8e51-688431054fb0.png)

Because of this, the correct fit parameters are skipped over by the MINUIT program and a bad compromise is reached.
![screenshot](https://cloud.githubusercontent.com/assets/3489773/6955318/8065e5da-d890-11e4-90ec-107fe4ffdaf4.png)

Zeroing out that option seems to work although there is still some funny behavior on the ends (but I think it is masked out and not counted in the actual minimization process)
![screenshot](https://cloud.githubusercontent.com/assets/3489773/6955320/9016d034-d890-11e4-98cc-ffc1b8441a6b.png)

**Comment by captainkirkby** [comment]
Still Todo:
The 'high' value looks a little low from the graphs
Edge detection is still implemented the by looking for crossings at a certain height

**Comment by dkirkby** [comment]
I was just noticing the same thing about high values being consistently a
bit low.

**Comment by captainkirkby** [comment]
I don't think that's my algorithm because MINUIT independently minimizes that error.

**Comment by captainkirkby** [comment]
Just for Documentation: the --spline-pad option specifies how far beyond the outer two crossings the template and the fitting should extend.  

Zero is always a safe option but the maximum safe value is a function of the height of the crossing (75% of hi right now) and the number of samples before the trigger (50 right now).

**Comment by captainkirkby** [comment]
New Edge Detection algorithm:

http://nbviewer.ipython.org/gist/captainkirkby/fae36de1f462d3599674

**Comment by captainkirkby** [comment]
The maximum safe spline pad is given by the expression

![Expression](https://cloud.githubusercontent.com/assets/3489773/7029499/fa7d86a8-dd12-11e4-9abc-4dd4204560b4.png)

**Comment by captainkirkby** [comment]
TODO:
Call this...

```./fit.py --show-plots --load-template db --show-centers --show-levels --spline-pad 0.03 --verbose --fetch-limit 100 --replay ~/runningDataWithGlitch.dat```

...and investigate why sometimes the high level is preferred over the notch height.

**Comment by dkirkby** [comment]
The notch looks a lot higher now, but I suppose that's a good test of the
robustness of your algorithm.

**Comment by captainkirkby** [comment]
Sometimes (about once a minute) the input data has two discrete high levels that look the same, but in the histogram there are two peaks (especially clear in the smooth version).  In this case, we count the number of peaks and if there are more than 3 (lo,mid,hi) then get rid of one of the two that are close together.

![screenshot](https://cloud.githubusercontent.com/assets/3489773/7100310/4d8bedf4-dfce-11e4-839e-5032f3883050.png)

Watch the parameters introduced in fit.py especially sharpThreshold.  If its too high, it may not find one of the levels.  Lowering it may increase computation time per frame.
