### ISSUE TITLE
BME 280 Support

### ISSUE THREAD

**Issue by captainkirkby** [captainkirkby/Gears#57]
Version 2.0 of the board uses the BME280 integrated environmental sensor (datasheet [here](http://ae-bst.resource.bosch.com/media/products/dokumente/bme280/BST-BME280_DS001-10.pdf)).  We need to add support for this chip in a header file called BME280.h

**Comment by captainkirkby** [comment]
For some reason the test program (serialTest.js) reads Big Endian ints, but the logger program (logger.js) reads Little Endian ints off the micro.  But it works except for the humidity sensor being stuck at 100% (current humidity is 77%)

**Comment by dkirkby** [comment]
Are both boards reading 100% RH ?
